_commit: 3e45c82
_src_path: https://github.com/yanbo-huang/fastapi-backend-template
db_password: admin
db_user_name: admin
include_precommit: false
project_description: novel-app-backend
project_name: novel-app-backend
