"""empty message

Revision ID: 623ee37dfbd5
Revises: e3ce02affe56
Create Date: 2024-07-03 18:31:26.500447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623ee37dfbd5'
down_revision: Union[str, None] = 'e3ce02affe56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novels', 'status')
    # ### end Alembic commands ###
